=== cw1521/TrailMaps/website/assets/schema/trailmaps.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">


    <xs:element name="trailmaps" type="trailMapsList"></xs:element>
           

    <xs:complexType name="trail">
        <xs:sequence>
            <xs:element name="id" type="xs:int" />
            <xs:element name="name" type="xs:string" />
            <xs:element name="lat" type="xs:decimal" />
            <xs:element name="long" type="xs:decimal" />
            <xs:element name="difficulty" type="xs:string" />
            <xs:element name="url" type="xs:string" />
            <xs:element name="rating" type="xs:decimal" />
            <xs:element name="description" type="xs:string" />
            <xs:element name="directions" type="xs:string" />
            <xs:element name="length" type="xs:string" />
            <xs:element name="features" type="xs:string" />            
        </xs:sequence>
    </xs:complexType>



    <xs:complexType name="trailMapsList">
        <xs:sequence>
            <xs:element name="trail" type="trail" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>




</xs:schema>

=== cw1521/TrailMaps/website/assets/xml/trails.xml
<?xml version="1.0" encoding="UTF-8"?>

<trailmaps xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../schema/trailmaps.xsd">

    <trail>
        <id>286997</id>
        <name>USA</name>
        <lat>30.69839</lat>
        <long>-88.17975</long>
        <difficulty>Beginner</difficulty>
        <url>https://www.singletracks.com/bike-trails/usa/</url>
        <rating>4</rating>
        
        <description>Singletrack, roots, some sand, most hard pack, mostly flat, bridges over water.</description>
        <directions>Behind University of Southern Alabama</directions>

        <length>12.0</length>
        
        <features></features>
        
    </trail>

    <trail>
        <id>286997</id>
        <name>USA</name>
        <lat>30.69839</lat>
        <long>-88.17975</long>
        <difficulty>Beginner</difficulty>
        <url>https://www.singletracks.com/bike-trails/usa/</url>
        <rating>4</rating>
        
        <description>Singletrack, roots, some sand, most hard pack, mostly flat, bridges over water.</description>
        <directions>Behind University of Southern Alabama</directions>

        <length>12.0</length>
        
        <features></features>
        
    </trail>


</trailmaps>
