=== cw1521/TrailMaps/schema/trailquery.xsd
<?xml version="1.0" encoding="UTF-8" ?>



<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">
        
    <xs:element name="trailquery">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="location" type="locationType"></xs:element>
                <xs:element name="ratings" type="ratingSeq"></xs:element>
                <xs:element name="difficulties" type="difficultySeq"></xs:element>
                <xs:element name="minLength" type="lengthType"></xs:element>
                <xs:element name="maxLength" type="lengthType"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="locationType">
        <xs:sequence>
            <xs:element name="latitude" type="latitudeType"></xs:element>
            <xs:element name="longitude" type="longitudeType"></xs:element>         
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ratingSeq">
        <xs:sequence minOccurs="0" maxOccurs="5">
            <xs:element name="rating" type="ratingType"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="ratingType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="5"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="lengthType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0.0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="longitudeType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="-180.0"/>
            <xs:maxInclusive value="180.0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="latitudeType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="-90.0"/>
            <xs:maxInclusive value="90.0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="difficultySeq">
        <xs:sequence minOccurs="0" maxOccurs="5">
            <xs:element name="difficulty" type="difficultyType"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="difficultyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Beginner"/>
            <xs:enumeration value="Intermediate"/>
            <xs:enumeration value="Hard"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== cw1521/TrailMaps/website/assets/misc/query.xml
<trailquery xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../schema/trailquery.xsd">
    <latitude>20.34</latitude>
    <longitude>33.5</longitude>
    <ratings>
        <rating>2</rating>
        <rating>3</rating>
        <rating>4</rating>
    </ratings>
    <difficulties>
        <difficulty>Beginner</difficulty>
        <difficulty>Intermediate</difficulty>
    </difficulties>
    <minLength>4.5</minLength>
    <maxLength>10.0</maxLength>

</trailquery>
